### PR TITLE
Add researcher section to CoC

### PR DESCRIPTION
**Pull request by logankilpatrick**
Update to match: https://github.com/JuliaLang/www.julialang.org/blob/main/community/standards.md

### CODE REVIEW

**Comment by logankilpatrick** [comment]
CC @ViralBShah

**Comment by ViralBShah** [comment]
It would perhaps be best to use this as the master document, and then just link to it from julialang.org etc. so that we don't have to worry about multiple versions.

**Comment by logankilpatrick** [comment]
Or perhaps the opposite?

**Comment by ViralBShah** [comment]
You want the master copy in this repo so that the github tools know how to find.

**Comment by ericphanson** [comment]
It looks like the headings in this version don’t match the version this was copied from (h3’s vs just bold) so now the headings are slightly off here (looks like the following items are for researchers only).

**Pull request merged**
